spring:
  application:
    name: jumia-clone
  #    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5440/jumia-clone
    username: ${db_username}
    password: ${db_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show-sql: false
  main:
    allow-circular-references: true


server:
  port: 8080

cloud_name: ${cloud_name}
api_key: ${api_key}
api_secret: ${api_secret}

servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB

#jwt:
#  adminKey: ${jwt.adminKey}
#  expireTime: ${jwt.expireTime}
#  refreshTime: ${jwt.refreshTime}
jwt:
  token:
    secret_key: 645266556A586E3272357538782F413F4428472B4B6250655368566B59703373

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true

#pay_stack_url: ${pay_stack_url:}
#pay_stack_verify: ${pay_stack_verify:}
#pay_stack_secret: ${pay_stack_secret:}
